spring:
  datasource:
    url: jdbc:mysql://localhost:3306/game_doan_so?createDatabaseIfNotExist=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 1 day

# Cấu hình VNPAY
vnpay:
  tmnCode: 3Q8PW5V4 # Thay bằng mã TmnCode của bạn từ VNPAY
  hashSecret: KZXVP0WRGYVA8L0Z9FSWP5DNONYEMMAP # Thay bằng mã bí mật HashSecret của bạn từ VNPAY
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html # URL môi trường thử nghiệm (sandbox) của VNPAY
  returnUrl: http://localhost:3000/payment/return # URL chuyển hướng về Frontend sau khi thanh toán
  apiUrl: https://sandbox.vnpayment.vn/merchantv2/ # URL API của VNPAY
